import type { CatalogProduct } from "./types";

export const mockProducts: CatalogProduct[] = [
  {
    id: "cake-soft-rose",
    category: "cake",
    nameUz: "Atirgulli yumshoq tort",
    priceUZS: 124_000,
    styleTags: ["Yumshoq", "Romantik"],
    popularity: 78,
    vendorQuality: 82,
    active: true,
  },
  {
    id: "cake-classic-cream",
    category: "cake",
    nameUz: "Kremli klassik tort",
    priceUZS: 126_000,
    styleTags: ["Klassik"],
    popularity: 95,
    vendorQuality: 94,
    active: true,
  },
  {
    id: "cake-inactive-premium",
    category: "cake",
    nameUz: "Premium bayram torti",
    priceUZS: 121_000,
    styleTags: ["Yumshoq"],
    popularity: 99,
    vendorQuality: 99,
    active: false,
  },
  {
    id: "flowers-soft-white",
    category: "flowers",
    nameUz: "Oq va nozik gullar",
    priceUZS: 98_000,
    styleTags: ["Yumshoq", "Romantik"],
    popularity: 81,
    vendorQuality: 84,
    active: true,
  },
  {
    id: "flowers-classic-mix",
    category: "flowers",
    nameUz: "Klassik aralash guldasta",
    priceUZS: 101_000,
    styleTags: ["Klassik"],
    popularity: 93,
    vendorQuality: 95,
    active: true,
  },
  {
    id: "flowers-inactive-premium",
    category: "flowers",
    nameUz: "Premium gullar",
    priceUZS: 97_000,
    styleTags: ["Yumshoq"],
    popularity: 99,
    vendorQuality: 99,
    active: false,
  },
];

